// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0d5c98ZuC9bs9o3S37fLcFxNdW0f5Fpg',
    appId: '1:958996135318:web:819078ab5f27db569131b7',
    messagingSenderId: '958996135318',
    projectId: 'project-bed3c',
    authDomain: 'project-bed3c.firebaseapp.com',
    storageBucket: 'project-bed3c.firebasestorage.app',
    measurementId: 'G-W1CJRRPSTC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9N6W1yJ6yZyN1SHFo49JffEIxy-wVBwc',
    appId: '1:958996135318:android:22c3c39c8d07b3bb9131b7',
    messagingSenderId: '958996135318',
    projectId: 'project-bed3c',
    storageBucket: 'project-bed3c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD53XanqArhdufXKQhy25nmkvtI5CWaLkw',
    appId: '1:958996135318:ios:76053df7647ffd099131b7',
    messagingSenderId: '958996135318',
    projectId: 'project-bed3c',
    storageBucket: 'project-bed3c.firebasestorage.app',
    iosBundleId: 'com.example.todoAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD53XanqArhdufXKQhy25nmkvtI5CWaLkw',
    appId: '1:958996135318:ios:76053df7647ffd099131b7',
    messagingSenderId: '958996135318',
    projectId: 'project-bed3c',
    storageBucket: 'project-bed3c.firebasestorage.app',
    iosBundleId: 'com.example.todoAppFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0d5c98ZuC9bs9o3S37fLcFxNdW0f5Fpg',
    appId: '1:958996135318:web:f4bdf50c12d2a49e9131b7',
    messagingSenderId: '958996135318',
    projectId: 'project-bed3c',
    authDomain: 'project-bed3c.firebaseapp.com',
    storageBucket: 'project-bed3c.firebasestorage.app',
    measurementId: 'G-E9MMYD3HXY',
  );
}
